/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useCallback,useEffect,useState} from "react";import {admin} from "@/lib/api";import type {AdminBusiness,AdminIntegrationError,AdminUser,Page} from "@/lib/types";import {Alert,Empty,Spinner} from "./ui";
type Kind="businesses"|"users"|"integration-errors";type Row=AdminBusiness|AdminUser|AdminIntegrationError;
const date=(value:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";const cell="border-t border-white/10 p-4 align-top";
const statuses={businesses:["onboarding","trial","active","past_due","suspended","cancelled"],users:["invited","active","suspended","disabled"]};
export function AdminList({kind}:{kind:Kind}){const [result,setResult]=useState<Page<Row>|null>(null),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(1);const load=useCallback(()=>{const query=new URLSearchParams({page:String(page)});if(search.trim().length>=2&&kind!=="integration-errors")query.set("search",search.trim());if(status&&kind!=="integration-errors")query.set("status",status);const request=kind==="businesses"?admin.businesses(query):kind==="users"?admin.users(query):admin.integrationErrors(query);setError("");request.then(value=>setResult(value as Page<Row>)).catch(value=>setError(value.message))},[kind,page,search,status]);useEffect(()=>{load()},[load]);return <>{kind!=="integration-errors"&&<form className="mt-5 flex flex-wrap gap-3" onSubmit={event=>{event.preventDefault();setPage(1);load()}}><input aria-label="Search" className="field max-w-xs bg-white text-[#101914]" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search…"/><select aria-label="Status" className="field max-w-48 bg-white text-[#101914]" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="">All statuses</option>{statuses[kind].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select><button className="btn bg-white text-[#101914]">Apply</button></form>}{error?<div className="mt-6"><Alert>{error}</Alert></div>:!result?<Spinner/>:result.data.length===0?<div className="mt-6 text-[#101914]"><Empty title="No results" detail="The API returned no monitoring records."/></div>:<><div className="mt-6 overflow-x-auto rounded-2xl border border-white/15"><table className="w-full min-w-[800px] text-left text-sm"><Headers kind={kind}/><tbody>{result.data.map(row=>kind==="businesses"?<BusinessRow key={row.uuid} row={row as AdminBusiness}/>:kind==="users"?<UserRow key={row.uuid} row={row as AdminUser}/>:<ErrorRow key={row.uuid} row={row as AdminIntegrationError}/>)}</tbody></table></div>{result.meta.last_page>1&&<nav aria-label="Admin pagination" className="mt-5 flex justify-between"><button className="btn bg-white text-[#101914]" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {result.meta.current_page} of {result.meta.last_page}</span><button className="btn bg-white text-[#101914]" disabled={page>=result.meta.last_page} onClick={()=>setPage(value=>value+1)}>Next</button></nav>}</>}</>}
function Headers({kind}:{kind:Kind}){return <thead className="bg-white/10">{kind==="businesses"?<tr><th>Business</th><th>Status</th><th>Owner</th><th>Subscription</th><th>Created</th></tr>:kind==="users"?<tr><th>User</th><th>Status</th><th>Verified</th><th>Businesses</th><th>Created</th></tr>:<tr><th>Provider / operation</th><th>Severity</th><th>Message</th><th>Business</th><th>Occurred / resolved</th></tr>}</thead>}
function BusinessRow({row}:{row:AdminBusiness}){return <tr><td className={cell}><strong>{row.name}</strong></td><td className={`${cell} capitalize`}>{row.status}</td><td className={cell}>{row.owner?<>{row.owner.name}<small className="block text-white/60">{row.owner.email}</small></>:"—"}</td><td className={cell}>{row.subscription?<>{row.subscription.plan?.name||"Plan unavailable"}<small className="block capitalize text-white/60">{row.subscription.status}</small></>:"—"}</td><td className={cell}>{date(row.created_at)}</td></tr>}
function UserRow({row}:{row:AdminUser}){return <tr><td className={cell}><strong>{row.name}</strong><small className="block text-white/60">{row.email}</small></td><td className={`${cell} capitalize`}>{row.status}</td><td className={cell}>{row.email_verified_at?"Verified":"Not verified"}</td><td className={cell}>{row.business_count}</td><td className={cell}>{date(row.created_at)}</td></tr>}
function ErrorRow({row}:{row:AdminIntegrationError}){return <tr><td className={cell}><strong>{row.provider}</strong><small className="block text-white/60">{row.operation}{row.error_code?` · ${row.error_code}`:""}</small></td><td className={`${cell} capitalize`}>{row.severity}</td><td className={cell}>{row.message}</td><td className={cell}>{row.business?.name||"—"}</td><td className={cell}>{date(row.occurred_at)}<small className="block text-white/60">Resolved: {date(row.resolved_at)}</small></td></tr>}
