"use client";
import Link from "next/link";import {usePathname,useRouter} from "next/navigation";import {useEffect,useState} from "react";import {auth,businesses} from "@/lib/api";import type {Business,User} from "@/lib/types";import {Brand} from "./brand";
const items=[["Dashboard","/app","business.view"],["Leads","/app/leads","leads.view"],["Conversations","/app/conversations","conversations.view"],["Templates","/app/templates","conversations.view"],["Team","/app/team","members.view"],["Settings","/app/settings","business.manage"]];
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname(),router=useRouter(),[user,setUser]=useState<User|null>(null),[list,setList]=useState<Business[]>([]),[current,setCurrent]=useState<Business|null>(null),[open,setOpen]=useState(false);
 useEffect(()=>{const expired=()=>{localStorage.removeItem("leadreply_business_uuid");window.location.replace("/login")};window.addEventListener("leadreply:unauthorized",expired);return()=>window.removeEventListener("leadreply:unauthorized",expired)},[]);
 useEffect(()=>{Promise.all([auth.me(),businesses.list()]).then(([identity,result])=>{if(!identity.user.email_verified_at){router.replace("/verify-email");return}setUser(identity.user);setList(result.businesses);const stored=localStorage.getItem("leadreply_business_uuid"),selected=result.businesses.find(item=>item.uuid===stored)||result.businesses[0]||null;if(!selected){localStorage.removeItem("leadreply_business_uuid");router.replace("/app/select-business");return}localStorage.setItem("leadreply_business_uuid",selected.uuid);businesses.switch(selected.uuid).then(value=>setCurrent(value.business)).catch(()=>{localStorage.removeItem("leadreply_business_uuid");router.replace("/app/select-business")})}).catch(()=>router.replace("/login"))},[router]);
 const nav=<><div className="px-5 py-5"><Brand/></div><nav className="flex-1 space-y-1 px-3">{items.filter(([,,permission])=>!current||current.permissions.includes(permission)).map(([label,url])=><Link onClick={()=>setOpen(false)} key={url} href={url} className={`block rounded-xl px-3 py-2.5 text-sm font-semibold ${path===url||url!=="/app"&&path.startsWith(url+"/")?"bg-[#e4f0e8] text-[var(--brand-dark)]":"hover:bg-[#f0f4f1]"}`}>{label}</Link>)}</nav><div className="border-t border-[var(--line)] p-4 text-sm"><strong className="block truncate">{user?.name||"Loading…"}</strong><span className="muted block truncate">{user?.email}</span><button className="mt-3 text-sm font-bold text-red-700" onClick={async()=>{try{await auth.logout()}finally{localStorage.removeItem("leadreply_business_uuid");window.location.replace("/login")}}}>Log out</button></div></>;
 const switchWorkspace=async(uuid:string)=>{const value=await businesses.switch(uuid);localStorage.setItem("leadreply_business_uuid",value.business.uuid);window.location.replace("/app")};
 return <div className="min-h-screen md:grid md:grid-cols-[240px_1fr]"><aside className="desktop-only sticky top-0 flex h-screen flex-col border-r border-[var(--line)] bg-white">{nav}</aside>{open&&<div className="fixed inset-0 z-50 flex md:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-black/30" onClick={()=>setOpen(false)}/><aside className="relative flex h-full w-64 flex-col bg-white">{nav}</aside></div>}<div className="min-w-0"><header className="sticky top-0 z-20 flex h-17 items-center justify-between gap-3 border-b border-[var(--line)] bg-white/95 px-4 md:px-7"><button className="btn btn-secondary md:hidden" onClick={()=>setOpen(true)} aria-label="Open navigation">☰</button><select aria-label="Current workspace" className="field min-w-0 max-w-[260px]" value={current?.uuid||""} disabled={!current} onChange={event=>switchWorkspace(event.target.value)}>{list.map(item=><option value={item.uuid} key={item.uuid}>{item.name}</option>)}</select><div className="badge desktop-only">{current?.membership.role||"Workspace"}</div></header><main className="min-w-0 p-4 md:p-7">{current||path==="/app/select-business"?children:<div role="status" className="p-8 text-center muted">Resolving workspace…</div>}</main></div></div>}
